version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=my-secret-pwd
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql